language: node_js
node_js:
    - 4.2
before_script:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.8
    - npm install -g grunt-cli
script:
    - npm install
    - grunt
